### ISSUE TITLE
Add support for roles

### ISSUE THREAD

**Issue by hburn7** [5DigitWorldCup/2024API#10]
With JWT, a user's roles stay with them in an HTTP Cookie until they fully login again. A way around this is to have roles stored in the database, and check against that table every time a request comes in from an authorized user. I think we should do this.

At a minimum, we need the following roles:
1. Admin -- Allows privileged editing, such as removing a user from a team
2. Organizer -- Allows access to the submissions form

**Comment by L-Mario564** [comment]
I thin think the easiest route here to is have environment variables in the backend that store arrays containing osu! user IDs corresponding to the above roles. So for example, I want to add myself as an admin, so, I can have an env variable like:

```env
ADMIN_USER_IDS=[14544646]
```

And then when I log in, there's a check to see what role they're assigned (or removed), and sends the encrypted cookie. Pseudo-code:

```
const user = getUser();

if (user.osuUserId is in env.ADMIN_USER_IDS) {
  return cookie; // Cookie with a property that tells the frontend that I'm in fact an admin
}
```

And same thing would go for organizers. This is probably the easiest way to do it, as implementing an endpoint and a UI to remove and add admins and organizers it a bit overkill for what's just a few select users.
